test:express.o queue.o list.o bitree.o
	gcc -g -o  test express.o queue.o list.o bitree.o
express.o:express.c 
	gcc -g -c  express.c
queue.o:queue.c 
	gcc -g -c  queue.c 
list.o:list.c
	gcc -g -c  list.c
bitree.o:bitree.c
	gcc -g -c  bitree.c
clean:
	rm test *.o
